Repository yeonju51/c_adventure_game, pull requests merged in 2024-06, with the labels that each got.

#7 Bug: 초기화되지 않은 메모리 사용 오류 수정
  main.c
Labels: Bug

#2 예외처리 및 가시성 추가
  main.c
Labels: Enhancement, CleanCode

#8 Bug: 크로스 플랫폼 호환성 보장을 위한 에러 수정
  main.c
Labels: Bug

#9 Bug fix: 플랫폼 간 SLEEP 매크로 시간 단위 차이 및 중복 정의 에러 수정
  main.c
Labels: Bug

#10 Modularize
  TextAdventureGame
  dungeon.c
  dungeon.h
  global.c
  global.h
  main
  main.c
  output.exe
  player.c
  player.h
  playerinfo.h
  tools.c
  tools.h
  utils.h
Labels: Refactor, CleanCode

#11 Modularize
  dungeon.c
  global.c
  global.h
  main.c
  output.exe
  player.c
  playerinfo.h
  tools.c
  tools.h
Labels: Bug, Refactor, CleanCode

#12 Clean: diece -> dice 오타 수정 및 scanf_s -> scanf로 mac OS 위한 변경
  dungeon.c
  tools.c
Labels: CleanCode

#13 Enhancement: tools모듈에 대한 단위테스트 함수 작성
  tools.c
  tools_test.c
Labels: CleanCode, Test

#15 Refactor: 입력함수 수정 & Bug: dice 버그 해결
  dungeon.c
  dungeon.h
  global.c
  global.h
  player.c
  tools.c
  tools.h
  tools_test.c
  utils.c
  utils.h
Labels: Bug, Enhancement, Refactor, CleanCode

#17 Enhancement: player모듈에 대한 단위테스트 함수 작성
  player_test.c
Labels: Enhancement, Test

#18 Enhancement: player모듈에 대한 단위 테스트 함수 작성
  player_test.c
Labels: Enhancement, Test

#19 Fix: test_checkForExit()함수 수정
  tools_test.c
Labels: Fix

#20 Clean: choosePath()함수에서 경로 결정 시 새로 만든 getIntInput()함수삭제
  dungeon.c
  tools.c
  tools.h
Labels: CleanCode

#21 Clean: prevent hard coding in initPlayerStats
  player.c
Labels: CleanCode
